#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${AZURE_BOOTSTRAP_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TF_DIR="$ROOT_DIR/terraform-azure"
TFVARS_FILE="$TF_DIR/terraform.tfvars"

if [[ -f "$TFVARS_FILE" ]]; then
  echo "terraform.tfvars already exists at $TFVARS_FILE"
  exit 0
fi

REQUIRED_VARS=(
  AZURE_RESOURCE_GROUP_NAME
  AZURE_LOCATION
  AZURE_STORAGE_ACCOUNT_NAME
  AZURE_KEY_VAULT_NAME
  AZURE_POSTGRES_SERVER_NAME
  AZURE_POSTGRES_ADMIN_PASSWORD
  AZURE_EVENTHUB_NAMESPACE_NAME
  AZURE_LOG_ANALYTICS_WORKSPACE_NAME
)

for var_name in "${REQUIRED_VARS[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "Missing required environment variable: $var_name" >&2
    exit 1
  fi
done

cat > "$TFVARS_FILE" <<EOF
resource_group_name        = "${AZURE_RESOURCE_GROUP_NAME}"
location                   = "${AZURE_LOCATION}"
project_name               = "lakehouse"
environment                = "dev"
storage_account_name       = "${AZURE_STORAGE_ACCOUNT_NAME}"
storage_container_name     = "warehouse"
key_vault_name             = "${AZURE_KEY_VAULT_NAME}"
postgres_server_name      = "${AZURE_POSTGRES_SERVER_NAME}"
postgres_admin_username   = "lakehouse"
postgres_admin_password   = "${AZURE_POSTGRES_ADMIN_PASSWORD}"
postgres_database_name    = "iceberg_catalog"
eventhub_namespace_name   = "${AZURE_EVENTHUB_NAMESPACE_NAME}"
eventhub_name             = "lakehouse-events"
log_analytics_workspace_name = "${AZURE_LOG_ANALYTICS_WORKSPACE_NAME}"
EOF

echo "Created $TFVARS_FILE"

# If the required Azure runtime variables are present, seed a skeleton .env.azure
# so the user can fill in the remaining values after terraform apply.
ENV_AZURE_FILE="$ROOT_DIR/.env.azure"
if [ -f "$ENV_AZURE_FILE" ]; then
  exit 0
fi

if [ -z "${AZURE_STORAGE_ACCOUNT_NAME:-}" ] || \
   [ -z "${AZURE_POSTGRES_HOST:-}" ] || \
   [ -z "${AZURE_EVENTHUB_NAMESPACE:-}" ] || \
   [ -z "${AZURE_KEY_VAULT_NAME:-}" ] || \
   [ -z "${AZURE_SP_CLIENT_ID:-}" ] || \
   [ -z "${AZURE_SP_CLIENT_SECRET:-}" ] || \
   [ -z "${AZURE_TENANT_ID:-}" ]; then
  exit 0
fi

cat > "$ENV_AZURE_FILE" <<EOF
# Skeleton Azure deployment profile generated by scripts/azure/bootstrap.sh
# Fill in the remaining values from terraform-azure outputs and run:
#   just azure-generate-config
LAKEHOUSE_PROFILE=azure

POSTGRES_HOST=${AZURE_POSTGRES_HOST}
POSTGRES_PORT=${AZURE_POSTGRES_PORT:-5432}
POSTGRES_USER=${AZURE_POSTGRES_USER:-lakehouse}
POSTGRES_PASSWORD=${AZURE_POSTGRES_PASSWORD:-}
POSTGRES_DB=${AZURE_POSTGRES_DB:-iceberg_catalog}

AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME:-warehouse}
AZURE_STORAGE_BLOB_ENDPOINT=
AZURE_STORAGE_PRIMARY_ACCESS_KEY=
AZURE_MLFLOW_ARTIFACTS_CONTAINER_NAME=${AZURE_MLFLOW_ARTIFACTS_CONTAINER_NAME:-mlflow-artifacts}

AZURE_EVENTHUB_NAMESPACE=${AZURE_EVENTHUB_NAMESPACE}
AZURE_EVENTHUB_NAME=${AZURE_EVENTHUB_NAME:-lakehouse-events}
AZURE_EVENTHUB_CONNECTION_STRING=
KAFKA_BOOTSTRAP_SERVERS=${AZURE_EVENTHUB_NAMESPACE}.servicebus.windows.net:9093

AZURE_KEY_VAULT_NAME=${AZURE_KEY_VAULT_NAME}
AZURE_KEY_VAULT_URI=

AZURE_ACR_LOGIN_SERVER=

UNITY_CATALOG_URI=
MLFLOW_TRACKING_URI=

AZURE_SP_CLIENT_ID=${AZURE_SP_CLIENT_ID}
AZURE_SP_CLIENT_SECRET=${AZURE_SP_CLIENT_SECRET}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
EOF

echo "Created $ENV_AZURE_FILE"
